name: chem_native
channels:
  - conda-forge
dependencies:
  - appnope=0.1.4=pyhd8ed1ab_0
  - asttokens=3.0.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - brotli=1.2.0=hca488c2_0
  - brotli-bin=1.2.0=hce9b42c_0
  - brotli-python=1.0.9=py38h2b1e499_8
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h6a3b0d2_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.0=py38h858044d_0
  - chardet=5.2.0=py38h10201cd_1
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - cloudpickle=3.1.0=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.1.1=py38h9afee92_1
  - cpp-expected=1.3.1=h4f10f1e_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.8.5=py38h11842c7_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - fmt=12.0.0=h669d743_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.53.1=py38h3237794_0
  - freetype=2.14.1=hce30654_0
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - greenlet=3.0.3=py38hb9fa5a8_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib-resources=6.4.5=pyhd8ed1ab_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.12.2=pyhd1c38e8_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.8.1=pyh31011fe_0
  - kiwisolver=1.4.5=py38h9afee92_1
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libarchive=3.8.2=gpl_h46575ef_100
  - libblas=3.9.0=20_osxarm64_openblas
  - libboost=1.84.0=hc9fb7c5_7
  - libboost-python=1.84.0=py38he25cb4c_5
  - libbrotlicommon=1.2.0=h87ba0bc_0
  - libbrotlidec=1.2.0=h95a88de_0
  - libbrotlienc=1.2.0=hb1b9735_0
  - libcblas=3.9.0=20_osxarm64_openblas
  - libcurl=8.16.0=hdece5d2_0
  - libcxx=21.1.4=hf598326_0
  - libdeflate=1.24=h5773f1b_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libglib=2.86.0=he69a767_1
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.0=h5505292_0
  - liblapack=3.9.0=20_osxarm64_openblas
  - libllvm14=14.0.6=hd1a9a77_4
  - liblzma=5.8.1=h39f12f2_2
  - liblzma-devel=5.8.1=h39f12f2_2
  - libmamba=2.3.3=h1370271_2
  - libnghttp2=1.67.0=hc438710_0
  - libopenblas=0.3.25=openmp_h6c19121_0
  - libpng=1.6.50=h280e0eb_1
  - libpq=16.10=hccc6603_2
  - librdkit=2024.03.5=h54a62e4_3
  - libsodium=1.0.18=h27ca646_1
  - libsolv=0.7.35=h5f525b2_0
  - libsqlite=3.50.4=h4237e3c_0
  - libssh2=1.11.1=h1590b86_0
  - libtiff=4.7.1=h7dc4979_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.15.1=h9329255_0
  - libxml2-16=2.15.1=h0ff4647_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.4=h4a912ad_0
  - llvmlite=0.41.1=py38hbed3d3f_0
  - lz4-c=1.10.0=h286801f_1
  - lzo=2.10=h925e9cb_1002
  - mamba=2.3.3=hb90242b_2
  - matplotlib=3.7.3=py38h150bfb4_0
  - matplotlib-base=3.7.3=py38hef9d0d7_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nlohmann_json-abi=3.12.0=h0f90c79_1
  - numba=0.58.1=py38hbe32c8a_0
  - numpy=1.24.4=py38ha84db1f_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.5.4=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.0.3=py38hefb543e_1
  - parso=0.8.4=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.46=h7125dd6_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py38h2c6aaed_0
  - pip=24.3.1=pyh8b19718_0
  - pixman=0.46.4=h81086ad_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - prompt_toolkit=3.0.48=hd8ed1ab_1
  - psutil=6.0.0=py38h3237794_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pycairo=1.26.1=py38he394224_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.20=h7d35d02_2_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.8=8_cp38
  - pytz=2024.2=pyhd8ed1ab_0
  - pyzmq=26.2.0=py38h7e0d939_0
  - rdkit=2024.03.5=py38h206a295_3
  - readline=8.2=h1d1bf99_2
  - reportlab=4.2.2=py38h3237794_0
  - reproc=14.2.5.post0=h5505292_0
  - reproc-cpp=14.2.5.post0=h286801f_0
  - requests=2.32.3=pyhd8ed1ab_0
  - rlpycairo=0.2.0=pyhd8ed1ab_0
  - scikit-learn=1.3.2=py38he1bc1c9_2
  - scipy=1.10.1=py38h038e806_3
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - setuptools=75.3.0=pyhd8ed1ab_0
  - shap=0.44.1=cpu_py38h4601ea3_0
  - simdjson=4.0.7=ha7d2532_0
  - six=1.16.0=pyh6c4a22f_0
  - slicer=0.0.7=pyhd8ed1ab_0
  - sqlalchemy=2.0.32=py38h3237794_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.1=py38hd97cf01_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=h892fb3f_2
  - tornado=6.4.1=py38h3237794_0
  - tqdm=4.67.1=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - unicodedata2=15.1.0=py38hb192615_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xz=5.8.1=h9a6d368_2
  - xz-gpl-tools=5.8.1=h9a6d368_2
  - xz-tools=5.8.1=h39f12f2_2
  - yaml-cpp=0.8.0=ha1acc90_0
  - zeromq=4.3.5=hcc0f68c_4
  - zipp=3.21.0=pyhd8ed1ab_0
  - zstandard=0.19.0=py38hb991d35_0
  - zstd=1.5.7=h6491c7d_2
  - pip:
    - chembl-webresource-client==0.10.9
    - lightgbm==4.6.0

prefix: "/Users/gabrielgravina/.local/share/mamba/envs/chem_native"
